# Нагадування по Markdown

Надаємо невелике нагадування записів в
[Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb) (LaTeX):

Markdown | Preview
--- | ---
`**bold text**` | **bold text**
 \\$\frac{x}{y}\\$ | $\frac{x}{y}$
 \\$p^{x}_{y}\\$ | $p^{x}_{y}$
\\$x \cdot y\\$ | $x \cdot y$
\\$\sqrt{x}\\$ | $\sqrt{x}$
\\$\pi\\$ | $\pi$
\\$\approx\\$ | $\approx$

І ще декілька прикладів:

```markdown
$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

 $$
 I =
 \left (\begin{array}{cc}
 1 & 0\\
 0 & 1
 \end{array}\right)
 $$
```

$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

$I =
\left (\begin{array}{cc}
1 & 0\\
0 & 1
\end{array}\right)$
 ---

# Завдання 1.
В шаблоні наведені числові вектори $\overline{a}$ та $\overline{b}$. Порахуй наступне:
- сума $\overline{a}$ та $\overline{b}$
- різниця $\overline{a}$ та $\overline{b}$
- сума $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}^T$.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- добуток Адамара (Hadamard product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.

In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

res = a + b

print(res)

[[1.5 3.  5.  7.  9. ]]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

res = a - b

res

array([[0.5, 1. , 1. , 1. , 1. ]])

In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

b_transposed = np.transpose(b)

res = a + b_transposed
print(res)

[[1.5 2.5 3.5 4.5 5.5]
 [2.  3.  4.  5.  6. ]
 [3.  4.  5.  6.  7. ]
 [4.  5.  6.  7.  8. ]
 [5.  6.  7.  8.  9. ]]



У бібліотеці numpy, при виконанні операцій, таких як додавання, над масивами
з різними формами, numpy автоматично розгортає масиви, щоб зробити їх сумісними
для операції. Це називається трансляцією.

Трансляція працює шляхом розтягнення або дублювання значень масивів вздовж
відсутніх розмірностей так, щоб вони відповідали формі іншого масиву.

Після трансляції обидва масиви матимуть форму 5x5, і numpy буде виконувати
елементне додавання:

```
a = [[1, 2, 3, 4, 5],    b_transposed = [[1/2, 1/2, 1/2, 1/2, 1/2],
     [1, 2, 3, 4, 5],                     [1, 1, 1, 1, 1],
     [1, 2, 3, 4, 5],                     [2, 2, 2, 2, 2],
     [1, 2, 3, 4, 5],                     [3, 3, 3, 3, 3],
     [1, 2, 3, 4, 5]]                     [4, 4, 4, 4, 4]]
```

Тепер numpy просто додасть відповідні елементи a та b_transposed

In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

b_transposed = np.transpose(b)

res = np.dot(a, b_transposed)
res

array([[40.5]])

Оскільки a має форму (1, 5), а b_transposed має форму (5, 1) після транспонування b, їх форми сумісні для множення матриць. Операція скалярного добутку результатує у скалярне значення, а не матрицю, оскільки результат множення рядкового вектора на стовпчиковий вектор - це одне скалярне значення.

Отже, у цьому випадку numpy не буде виконувати трансляцію, і операція скалярного добутку буде виконуватися так, як очікувалося, результатом буде скалярне значення.

In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

res = np.dot(a, b)
res

Щоб виконати скалярний добуток двох матриць за допомогою функції np.dot() бібліотеки numpy, матриці повинні бути сумісними для множення матриць. Це означає, що кількість стовпців у першій матриці повинна бути рівною кількості рядків у другій матриці.

У наданому прикладі матриця a має форму (1, 5), а матриця b має форму (1, 5). Скалярний добуток між цими двома матрицями неможливий, оскільки кількість стовпців у a (5) не відповідає кількості рядків у b (1).

Оскільки форми a та b не можуть бути транслювані для забезпечення сумісності для множення матриць, numpy викине ValueError, вказавши, що форми не вирівняні для операції скалярного добутку.

In [ ]:
a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

res = a * b
res

Добуток Aдамара, також відомий як елементне множення, - це операція, яка виконується над двома матрицями з однаковими розмірами в бібліотеці NumPy. При цьому кожен елемент результуючої матриці є добутком відповідних елементів вихідних матриць. У NumPy цю операцію можна виконати швидко та ефективно за допомогою оператора *.

In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

res = a / b
res

array([[2.        , 2.        , 1.5       , 1.33333333, 1.25      ]])

Обидві матриці мають розмірність 1x5. Операція елементного ділення проводиться покоординатно: кожний елемент матриці a ділиться на відповідний елемент матриці
b. Результат цієї операції - нова матриця res, яка також має розмірність 1x5, і в якій кожен елемент - результат ділення відповідних елементів матриць та b.

In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

b_transposed = np.transpose(b)
res = a / b_transposed
res

array([[ 2.        ,  4.        ,  6.        ,  8.        , 10.        ],
       [ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ],
       [ 0.5       ,  1.        ,  1.5       ,  2.        ,  2.5       ],
       [ 0.33333333,  0.66666667,  1.        ,  1.33333333,  1.66666667],
       [ 0.25      ,  0.5       ,  0.75      ,  1.        ,  1.25      ]])

NumPy автоматично розширює масив a для відповідності розмірності з масивом b_transposed, який має розмірність (5, 1), тобто він має одну колонку, але п'ять рядків. При цьому розширенні NumPy копіює рядки a, щоб вони відповідали кількості рядків у b_transposed.

Отже, операція ділення виконується поелементно між розширеними a та b_transposed, що призводить до отримання результуючої матриці розмірністю (5, 5)

# Завдання 2
В цьому завданні ти навчишся перетворювати вектори за допомогою афінних перетворень.  
Дано вектор:
$$
x =
\left(\begin{array}{cc}
2\\
1
\end{array}\right)
$$


Виконай аналітично наступні завдання задавши матрицю перетворення та застосуй її до вектора $x$:

1. Зменши вектор $x$ в 2 рази по вісі $OX$ та збільш в 3 рази по вісі $OY$.
2. Відобрази вектор $x$ відносно початку координат.
3. Перенеси вектор $x$ на -3 по вісі $OX$ та на 1 по вісі $OY$.
4. Змісти вектор $x$ на 60° по вісі $OY$.
5. Поверни вектор $x$ на 30°.
6. Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

#### 2.1 Зменши вектор  $x$  в 2 рази по вісі  OX  та збільш в 3 рази по вісі  OY .

$$
M_1 = \left (\begin{array}{cc}
0.5 & 0\\
0 & 3
\end{array}\right)
\\
M_1x = \left (\begin{array}{cc}
1\\
3
\end{array}\right)
\\
$$

#### 2.2 Відобрази вектор $x$ відносно початку координат.

$$
M_2 = \left (\begin{array}{cc}
-1 & 0\\
0 & -1
\end{array}\right)
\\
M_2x = \left (\begin{array}{cc}
-2\\
-1
\end{array}\right)
\\
$$



#### 2.3 Перенеси вектор $x$ на -3 по вісі $OX$ та на 1 по вісі $OY$.

$$
M_3 = \left (\begin{array}{cc}
1 & 0 & -3\\
0 & 1 & 1\\
0 & 0 & 1
\end{array}\right)
\\
\\
M_3x = \left (\begin{array}{cc}
-1\\
2
\end{array}\right)
\\
$$

#### 2.4 Змісти вектор $a$ на 60° по вісі $OY$.


$$
M_4 = \left (\begin{array}{cc}
1 & 0\\
\sqrt{3} & 1
\end{array}\right)
\\
\\
M_4x = \left (\begin{array}{cc}
2 + \sqrt{3}\\
1
\end{array}\right)
\\
$$

#### 2.5 Поверни вектор $a$ на 30°.

$$
M_5 = \left (\begin{array}{cc}
\frac{\sqrt{3}}{2} & -\frac{1}{2}\\
\frac{1}{2} & \frac{\sqrt{3}}{2}
\end{array}\right)
\\
\\
M_5x = \left (\begin{array}{cc}
\sqrt{3} - \frac{1}{2}\\
\frac{1}{2} + \sqrt{3}
\end{array}\right)
\\
$$

#### 2.6 Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$

$$
M_6 = M_5 \cdot M_4 \cdot M_2 \cdot M_1 = ?
$$

$$
M_6 =
\left (\begin{array}{cc}
0 & 1\frac{1}{2}\\\
1 & \frac{-3\sqrt{3}}{2}
\end{array}\right)
\\
M_6x = \left (\begin{array}{cc}
-1.4\\
-4.59808
\end{array}\right)
$$

# Завдання 2 (Альтернативне)

In [ ]:
import cv2 as cv
import urllib
import numpy as np

#   Функція для створення матриці перетворення з масштабуванням

def scaling_matrix(scale_x, scale_y):
    return np.array([[scale_x, 0], [0, scale_y]])

#   Функція для створення матриці перетворення з обертанням на кут angle
# у градусах

def rotation_matrix(angle):
    angle_rad = np.radians(angle)
    cos_theta = np.cos(angle_rad)
    sin_theta = np.sin(angle_rad)
    return np.array([[cos_theta, -sin_theta], [sin_theta, cos_theta]])

#   Функція для створення матриці горизонтального зсуву кут angle
# у градусах
def vertical_shift_matrix(shift_angle):
    angle_rad = np.radians(shift_angle)
    tan_theta = np.tan(angle_rad)
    return np.array([[1, 0], [tan_theta, 1]])

# Функція для створення матриці перетворення з переміщенням на dx по X і dy по Y
def translation_matrix(dx, dy):
    return np.array([[1, 0, dx], [0, 1, dy]])

# Вектор x

x = np.array([[2], [1]])

#   Задання матриці для зменшення в 2 рази по вісі OX та збільшення
# в 3 рази по вісі OY

scaling_matrix_M1 = scaling_matrix(0.5, 3)

# Задання матриці для відображення відносно початку координат
reflection_matrix_M2 = np.array([[-1, 0], [0, -1]])

# Задання матриці для повороту на 60° по вісі OY
vertical_shift_matrix_1_M4 = vertical_shift_matrix(60)

# Задання матриці для повернення на 30°
rotation_matrix_2_M5 = rotation_matrix(30)

# Об'єднання матриць перетворень
combined_matrix = rotation_matrix_2_M5 @ vertical_shift_matrix_1_M4 @ reflection_matrix_M2 @ scaling_matrix_M1

# Застосування об'єднаної матриці перетворення до вектора x
transformed_x = combined_matrix @ x

# Виведення результату
print("Transformed x:")
print(transformed_x)

Transformed x:
[[ 1.5       ]
 [-4.59807621]]
